title: Anjaney Parasar # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  •	I have a passion for machine learning and AI. I have a strong foundation in Python programming, statistics, visualisation, SQL and machine learning algorithms. In my spare time, I work on personal projects related to sales forecasting, recommender systems, etc. I have developed a number of successful models that can be used by businesses to improve their sales and customer satisfaction.
  <br><br>
 •	I am eager to learn and grow in this field. I am also a skilled communicator and team player. I am confident that i can make a significant contribution to any team. I am hard worker and always willing to go the extra mile. 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
